name: CI reports

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
        
    name: Build with Java 8
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-
      
      - name: Build with Maven
        run: >
          mvn -f myproject/pom.xml verify
          -Pjacoco
          -DrepoToken=$COVERALLS_REPO_TOKEN
          -DpullRequest=${{ github.event.pull_request.number }}
          coveralls:report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        
      - name: Generate JUnit report
        run: >
          mvn -f myproject/pom.xml
          surefire-report:report-only site:site -DgenerateReports=false
        if: ${{always()}} 
      - name: Archive JUnit Report
        uses: actions/upload-artifact@v2
        if: ${{always()}} 
        with:
          name: surefire-report
          path: '**/target/site'
