name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
        
    name: Build with Java 8
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-
      
      - name: Build with Maven
        run: >
          mvn -f myproject/pom.xml
          clean verify
          surefire-report:report-only site:site -DgenerateReports=false
          
      - name: Archive JUnit Report
        uses: actions/upload-artifact@v2
        with:
          name: surefire-report
          path: '**/target/site'
